### ISSUE TITLE
Outstanding work on status endpoint

### ISSUE THREAD

**Issue by bwhm** [Joystream/status-endpoint-joystream#7]
#### Types
The most important is to update types for constantinople.

### Burn
To avoid the concept of also tracking tokens yet to be burned, I would like to burn as soon as it is received. It is actually fairly easy to create a tx that includes the tip, thus allowing us to burn instantly.

1. Import the seed for the address (`receiveAddress`) being monitored as a new `.env` 
2. Set your keypair
3. Keep 1 joy/token in on the `receiveAddress`
4. Let the incoming amount be `n`
```
  const txHash = await get.api.tx.balances
  .transfer(receiveAddress, 1)
  .signAndSend(keypair, {tip: n});
```

**Comment by Gamaranto** [comment]
Types added in #8

**Comment by Lezek123** [comment]
Done in https://github.com/Joystream/status-endpoint-joystream/pull/9
